### ISSUE TITLE
we should use another package name

### ISSUE THREAD

**Issue by OleksandrKucherenko** [klarna/react-native-klarna-inapp-sdk#10]
https://github.com/klarna/react-native-klarna-inapp-sdk/blob/86c73ef7b9e47a9c04775ceb304fe2bfa01fa990/android/src/main/AndroidManifest.xml#L2

when we try to include the SDK into Klarna application that uses package `com.klarna` we have a DEX conflict.

All modules/libraries should use own unique package name. 

P.S. Its ok for the rest of the world, but for internal use we create conflict.

P.P.S. workaround:

```gradle
android {
    /* ... */
    /* Custom source code injection */
    sourceSets {
        // http://google.github.io/android-gradle-dsl/current/com.android.build.gradle.api.AndroidSourceSet.html
        main {
            /*
                Inject library source code into solution to prevent the conflict of
                the packages: App - com.klarna & InAppSdk - com.klarna
            */
            java.srcDirs project(':react-native-klarna-inapp-sdk').file('src/main/java')
        }
    }
}
```

recommended package name: `com.klarna.inapp.sdk` OR `com.klarna.inapp`

**Comment by omarbh** [comment]
Hi @OleksandrKucherenko! thanks for raising this, we will fix it in the next release!

**Comment by mahmoudjafarinejad** [comment]
Hi @OleksandrKucherenko @omarbh. This issue is fixed in the latest version by updating the package name.

**Comment by OleksandrKucherenko** [comment]
Thanks!
