### ISSUE TITLE
Android build fails

### ISSUE THREAD

**Issue by HalilFocic** [klarna/react-native-klarna-inapp-sdk#146]
**Describe the bug**
Gradle build fails while executing command `npm run android` on React Native

**To Reproduce**
1. `npx react-native init ProjectName`
2. `npm install react-native-klarna-inapp-sdk --save`
3. `react-native link react-native-klarna-inapp-sdk`
4. I reference repository in build.gradle file

**Expected behavior**
App build succeeds

**Screenshots**
<img src="https://i.ibb.co/nQpBN0S/image.png" style="display:block;"/>

**Device and version:**
 - Device: [Redmi Note 10 Pro]
 - OS: [Android 11]
 - SDK Version [2.1.6]

Additionally, if i remove klarna from dependencies, it would without any problems.

**Comment by fatlinesofcode** [comment]
their build.gradle is not compatible with gradle 7.
ive made a pr with the fix here
https://github.com/klarna/react-native-klarna-inapp-sdk/pull/150

**Comment by HalilFocic** [comment]
@fatlinesofcode First, thank you for fixing the problem. Second,  is there a way I can fix it for my app without having to wait for them to merge the request?

**Comment by fatlinesofcode** [comment]
@HalilFocic `npm install https://github.com/fatlinesofcode/react-native-klarna-inapp-sdk#patch-1 --save`

**Comment by HalilFocic** [comment]
Do I just do npm install and start using package or do I have to do the regular steps of linking in pods and gradle files? Thank you @fatlinesofcode

**Comment by HalilFocic** [comment]
I get SDK location was not found for Klarna. Do I need to insert it somewhere?

**Comment by NMGuner** [comment]
Hi, we are sorry for not taking care of this sooner but with the [2.1.8 version of the library](https://github.com/klarna/react-native-klarna-inapp-sdk/blob/master/CHANGELOG.md#218---2022-09-20), we rolled out a fix for Gradle 7 compatibility issue. Hence you should be able to use the package release via npmjs instead of a fork.

Please feel free to open this again if you still have the same problem.
