### ISSUE TITLE
Installation fails with 1.0.9

### ISSUE THREAD

**Issue by mchambaud** [klarna/react-native-klarna-inapp-sdk#20]
**Describe the bug**
Running `pod install` after SDK installation gives error

```
Fetching podspec for `react-native-klarna-inapp-sdk` from `../node_modules/react-native-klarna-inapp-sdk/react-native-klarna-inapp-sdk.podspec`
Downloading dependencies
Installing KlarnaMobileSDK (2.0.10)
Installing react-native-klarna-inapp-sdk (1.0.9)

[!] Error installing react-native-klarna-inapp-sdk
[!] /usr/bin/git clone https://github.com/klarna/react-native-klarna-inapp-sdk.git /var/folders/w2/hgd452qx5qv8jvq0r1k1fxv40000gn/T/d20200227-7880-p7tvpp --template= --single-branch --depth 1 --branch 1.0.9

Cloning into '/var/folders/w2/hgd452qx5qv8jvq0r1k1fxv40000gn/T/d20200227-7880-p7tvpp'...
warning: Could not find remote branch 1.0.9 to clone.
fatal: Remote branch 1.0.9 not found in upstream origin
```

**To Reproduce**
1. Manually install SDK
2. Go to iOS folder
3. pod install

**Expected behavior**
Should install without errors

**Screenshots**
<img width="1474" alt="image" src="https://user-images.githubusercontent.com/360109/75477105-c59c1480-5969-11ea-81f7-dd3bac6ee989.png">

**Device and version:**
 - Device: MacBook Pro
 - OS: MAX OS X
 - SDK Version 1.0.9

**Additional context**
We did not have issues with 1.0.7

**Comment by polar133** [comment]
Hi @mchambaud, thanks for your message. We looked into it and updated our release ta. Try again and please, run **pod repo update** before **pod install**. Let me know if that works.

**Comment by mchambaud** [comment]
Same issue

**Comment by polar133** [comment]
@mchambaud looking into it. I will notify you here any update.

**Comment by benirvingplt** [comment]
Hey - has this issue been resolved? Still the error when trying to pod install the latest version

**Comment by polar133** [comment]
Hi @benirvingplt , yes this issue was resolved. do you have the same issue or you are getting a different error ?

**Comment by benirvingplt** [comment]
Yeah it's fixed now
