### ISSUE TITLE
> Task  : react-native-klarna-inapp-sdk:compileReleaseJavaWithJavac FAILED

### ISSUE THREAD

**Issue by icarusdust** [klarna/react-native-klarna-inapp-sdk#233]
**Describe the bug**
I cannot say if it is a bug, but when I am integrating `react-native-klarna-inapp-sdk` into my project, and running `./gradlew assembleRelease`, it is failing with the following error. Refer to the screenshot.

**To Reproduce**
1. Follow the documentation to integrate Klarna SDK
2. Run the build command to build AAB or APK

**Screenshots**

<img width="1343" alt="Screenshot 2023-12-31 at 11 33 22" src="https://github.com/klarna/react-native-klarna-inapp-sdk/assets/43378371/8039cff6-bb26-4175-8d93-b8563368c8f5">

**Impact Level**
It is kind of urgent and blocking me from finishing my Android build.

**Comment by NMGuner** [comment]
Hi @icarusdust, the latest version of the library is developed using Java 11(similar to all recent RN libraries) and that seems to be causing this issue as I understand it. You may either need to use the previous version or update your project to use JDK 11. Can you please try one of these and let us know if it resolves this

**Comment by icarusdust** [comment]
Anything else to check ? @NMGuner

**Comment by Mohsin-PLT** [comment]
Facing the same issue while using JDK 15, any solution for this ?

**Comment by MasoudFallahpourbaee** [comment]
A new version is released (v2.2.1) that should resolve the issue.

**Comment by MasoudFallahpourbaee** [comment]
Closing. Fill free to re-open if you're still facing the issue with the latest version.
