### ISSUE TITLE
iOS - Multiple commands produce 'react_native_klarna_inapp_sdk.framework/Headers/KlarnaCheckoutViewWrapper.h'

### ISSUE THREAD

**Issue by LouisRaine** [klarna/react-native-klarna-inapp-sdk#250]
**Describe the bug**
When building for iOS using react native 0.73

IOS build fails due to Multiple commands produce 'react_native_klarna_inapp_sdk.framework/Headers/KlarnaCheckoutViewWrapper.h'

issue seems to arise from newarch and oldarch sharing Header names

```
Multiple commands produce '/Users/<User>/Library/Developer/Xcode/DerivedData/<TARGET>-arrtmfchdgicwxgzcygiolvxrmxl/Build/Products/Debug-iphonesimulator/react-native-klarna-inapp-sdk/react_native_klarna_inapp_sdk.framework/Headers/KlarnaCheckoutViewWrapper.h'

Target 'react-native-klarna-inapp-sdk' (project 'Pods') has copy command from '/Users/<User>/workspace/<TARGET>/<PROJECT_DIR>/node_modules/react-native-klarna-inapp-sdk/ios/Sources/view/oldarch/KlarnaCheckoutViewWrapper.h' to '/Users/<User>/Library/Developer/Xcode/DerivedData/<TARGET>-arrtmfchdgicwxgzcygiolvxrmxl/Build/Products/Debug-iphonesimulator/react-native-klarna-inapp-sdk/react_native_klarna_inapp_sdk.framework/Headers/KlarnaCheckoutViewWrapper.h'

Target 'react-native-klarna-inapp-sdk' (project 'Pods') has copy command from '/Users/<User>/workspace/<TARGET>/<PROJECT_DIR>/node_modules/react-native-klarna-inapp-sdk/ios/Sources/view/newarch/KlarnaStandaloneWebViewWrapper.h' to '/Users/<User>/Library/Developer/Xcode/DerivedData/<TARGET>-arrtmfchdgicwxgzcygiolvxrmxl/Build/Products/Debug-iphonesimulator/react-native-klarna-inapp-sdk/react_native_klarna_inapp_sdk.framework/Headers/KlarnaStandaloneWebViewWrapper.h'
```

**To Reproduce**

yarn add react-native-klarna-inapp-sdk

pod install

build project for react native 0.73

iOS simulator 15 Pro

react-native-klarna-inapp-sdk@2.3.0

**Comment by javier-28** [comment]
I have the same problem, any news ?

**Comment by sergio-33333** [comment]
I have the same problem, any news ? 🤔

**Comment by NMGuner** [comment]
Hi all, 2.3.2 has been released which doesn't have duplicate header files for the iOS implementation. Can you please try it and let us know if the issue persists. Unfortunately we have been unable to reproduce it in our project, thus can't verify for 100% if it's addressed.

**Comment by javier-28** [comment]
Hi, in my case, using the 2.3.2 version works!. Thanks, @NMGuner

**Comment by sergio-33333** [comment]
Works! 🚀  Thanks @NMGuner
