### ISSUE TITLE
Authorization window is not showing properly on iOS 13.1

### ISSUE THREAD

**Issue by olofekelund** [klarna/react-native-klarna-inapp-sdk#4]
When I try to load the authorization window it animates up and stays for a split second, then dissapears completely. This is on iOS 13.1 running on different simulators. Have not had the possibility to test it on an actual device though. I also tried it with v1.0.2 and v1.0.3 with no luck.

**Comment by deviousknight** [comment]
just update to a new version of ios klarna sdk

**Comment by olofekelund** [comment]
I tried updating to 2.0.6 with no luck. And CocoaPods gave me trouble when i tried version 2.0.8.

**Comment by olofekelund** [comment]
Sure! I'm running an ejected expo app, v34. The react native sdk version is 34.0.1. And i've linked the klarna RN sdk. 
I tried changing the sdk version in the podspec (react-native-klarna-inapp-sdk.podspec) to 2.0.6 but I get the same issue (the authorization window dissapears). When I try to use 2.0.8, CocoaPods says: 
``` [!] CocoaPods could not find compatible versions for pod "KlarnaMobileSDK":
  In snapshot (Podfile.lock):
    KlarnaMobileSDK (= 2.0.6, ~> 2.0.6)

  In Podfile:
    react-native-klarna-inapp-sdk (from `../node_modules/react-native-klarna-inapp-sdk`) was resolved to 1.0.3, which depends on
      KlarnaMobileSDK (~> 2.0.8)

Specs satisfying the `KlarnaMobileSDK (= 2.0.6, ~> 2.0.6), KlarnaMobileSDK (~> 2.0.8)` dependency were found, but they required a higher minimum deployment target. ```

**Comment by gbanfalvikl** [comment]
Hi, we found the issue and we're on it!

**Comment by olofekelund** [comment]
Hey! Are you making any progress on this?

**Comment by omarbh** [comment]
HI @olofekelund could you please try the latest version : 2.0.8 and see if this is still happening

**Comment by olofekelund** [comment]
I'm still getting the same error when I try to set 2.0.8. Maybe it's something about the way my project is set up. Anyway, I figured out another solution so I'm not using this package.

**Comment by omarbh** [comment]
Hi @olofekelund sorry for the late response. This is issue should be fixed in the latest version, could you please verify
