### ISSUE TITLE
Klarna WebView Not Properly rendering on Android 

### ISSUE THREAD

**Issue by kashif-javaid** [klarna/react-native-klarna-inapp-sdk#68]
On Android , if you try to render KlarnaPaymentView for category pay_over_time , the Webview is not fully rendered , It just shows the header part with breakdown of payments,  without the Card Input View where user would enter their card details . 

It seems like it has to do with Height listener in Android , because if you rotate your device and then bring it back , it layouts fine , the same code works fine for IOS .  

**To Reproduce**

some of the code is removed , but skeleton is there . 
`
import { KlarnaConfirmationFooter } from './klarna-confirmation-footer.component';

export const StyledKlarnaPaymentView = styled(KlarnaPaymentView)`
    width: 100%;
    flex: 1;
`;

export const KlarnaWebViewWrapper = styled.View`
    flex: 1;
`;

export const KlarnaConfirmationWrapper = styled.View`
    flex: 1;
`;

export const KlarnaConfirmation: React.FC = React.memo(function KlarnaConfirmation() {

    return (
        <KlarnaConfirmationWrapper>
            <KlarnaWebViewWrapper>
                {!isKlarnaLoaded && <ActivityIndicator size="large" />}
                {!isFetching && (
                    <StyledKlarnaPaymentView
                        category={chosenCategory as string}
                        ref={klarnaViewRef}
                        onInitialized={handleInitialised}
                        onLoaded={handleLoaded}
                        onAuthorized={eventCallBack}
                        onError={eventCallBack}
                        onFinalized={eventCallBack}
                        onReauthorized={eventCallBack}
                    />
                )}
            </KlarnaWebViewWrapper>
            <KlarnaConfirmationFooter disabled={isFooterButtonDisabled} onPress={handlePayWithKlarnaTap} />
        </KlarnaConfirmationWrapper>
    );
});

`
**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. This is from a physical Huwaei p30 lite 
![Screenshot_20201203_144752_and digital missguided](https://user-images.githubusercontent.com/69578001/101045913-8cd44000-3578-11eb-9edb-4de0a49b362c.jpg)

This is a from emulator  
![Screenshot_1607008178](https://user-images.githubusercontent.com/69578001/101047205-93af8280-3579-11eb-95a0-9882b704d817.png)

**Device and version:**
 - Huwaei P30 lite
 - Android Version 10.0
 - SDK Version 2.0.13

 - Galaxy J5
 - Android Version 7.1.1
 - SDK Version 2.0.13

**Additional context**

**Comment by kashif-javaid** [comment]
@NMGuner @polar133 Can you please look at this .

**Comment by NMGuner** [comment]
@kashif-javaid A [new version](https://github.com/klarna/react-native-klarna-inapp-sdk/releases/tag/v2.0.16) has been released with a fix for the content height issue on Android. Please try this one and inform us if the issue still persists.

**Comment by kashif-javaid** [comment]
Thanks @NMGuner .i will. Update you soon

**Comment by kashif-javaid** [comment]
@NMGuner unfortunately , the problem still persists 😓  , It still doesnt work fine for Pay_in_3 and works fine for 30 days .

**Comment by gbanfalvikl** [comment]
Hi @kashif-javaid , we have some issues reproducing this, any chance we could contact you privately?

**Comment by kashif-javaid** [comment]
HI @gbanfalvikl yeah you can contact me at kashif.javaid@and.digital

**Comment by NMGuner** [comment]
Hi, we investigated and contacted regarding this issue and closing it now. Please try newer versions and if you still experience this issue feel free to open an issue again.

**Comment by akhilsanker** [comment]
@NMGuner ,

Using the latest version and still facing the issue.

Thanks
