### ISSUE TITLE
Android soft keyboard hides the input field in bottom screen

### ISSUE THREAD

**Issue by ocea602** [klarna/react-native-klarna-inapp-sdk#80]
Hi,
Android soft keyboard hides the input field at bottom of screen and the content above the keyboard is not scrollable.
This makes a bad user experience since the users needs to write their info in blindfold (behind the soft keyboard).
This can be fixed by setting android:windowSoftInputMode="adjustResize" in Manifest.xml but that will change the behaviour on the soft keyboard in the whole app, which is not wanted in this case. It is only needed in the Klarna module. 

**Device and version:**
Samsung S20 FE Android 11

**Comment by NMGuner** [comment]
Hi @ocea602, thanks for reporting this issue. Is this for the input fields inside the authorize dialog that is fullscreen or do you mean the input fields available in the payment view(card details etc)?

**Comment by ocea602** [comment]
> Hi @ocea602, thanks for reporting this issue. Is this for the input fields inside the authorize dialog that is fullscreen or do you mean the input fields available in the payment view(card details etc)?

Hi! It is the fullscreen were you write your personal information like home address, phone and emailaddress

**Comment by NMGuner** [comment]
Hi @ocea602, recently we released a version(2.0.36) with a fix for keyboard issues in fullscreen. However, I would like to mention that this may not fix it for all users, it'll work for most of them. The limitation here is the WebView version, we noticed that devices running an older version are not working properly with keyboard changes. Please feel free to open a new issue if you still have a problem with the SDK.
